server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5448/crudms
    username: crudms
    password: crudms
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true

proxy-cache:
  enabled: true
  default-ttl-ms: 30000
